### PR TITLE
Feat/ios buffer config

### PR DESCRIPTION
**Pull request by FrikkieSnyman**
Similar to the existing bufferconfig that exists for exo player, minus the functionality of `minBufferMs` and `maxBufferMs`

### CODE REVIEW

**Comment by FrikkieSnyman** [comment]
Made a PR to the original package here: https://github.com/react-native-community/react-native-video/pull/1353

Will see what feedback I get there as well

**Comment by jochem725** [comment]
Cool! @FrikkieSnyman What is the benefit of this over the Apple implementation? I tried to look for the Apple implementation in the docs but I couldn't find it.

**Comment by FrikkieSnyman** [comment]
@jochem725 It should reduce the time-to-play on iOS.

Currently, iOS determines if playback should start by looking at the likelihood that the buffering will keep up with the playback. This causes a considerable higher amount to be downloaded before playback starts.

This implementation is similar to how the buffer config on Android works, as such that it will now only download the specified amount before playback starts, which should reduce our time-to-play the video on ios

**Comment by jochem725** [comment]
@FrikkieSnyman Nice :)

**Pull request merged**
